config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]
  resources :categories, except: [:destroy]
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 3, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 3000 }
    validates :user_id, presence: true
end

app/models/article_categories.rb
class ArticleCategories < ApplicationRecord
    belongs_to :category
    belongs_to :article
end

app/models/article_category.rb
class ArticleCategory  < ApplicationRecord
    belongs_to :category
    belongs_to :article
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :articles, through: :article_categories
    before_save { self.name = name.downcase}
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase}
    validates :username, presence: true, length: {minimum:3, maximum:25}, 
              uniqueness: { case_sensitive: false }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { minimum: 4, maximum: 254 },
              uniqueness: { case_sensitive: false },
              format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?, :current_user
    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    
    def logged_in?
        !!current_user
    end
    def require_user
        if !logged_in?
            flash[:danger] = "you must be login in"
            redirect_to root_path
        end
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:edit, :show, :update, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def index
        @articles = Article.paginate(page: params[:page], per_page: params[:limit])
    end
    def new
        @article = Article.new
    end
    def destroy
        @article.destroy
        flash[:danger] = "The article was succesfully deleted"
        redirect_to articles_path
    end
    def create
        # render plain: params[:article].inspect
        @article = Article.new(article_params)
        @article.user_id = current_user.id
        if @article.save
            flash[:success] = "Article was succesfully created"    
            redirect_to article_path(@article)
        else
            render 'new'
        end 
    end

    def show 
    end

    def edit 
    end
    
    def update
        if @article.update(article_params)
            flash[:success] = "Article was succesfully updated"    
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    private 
    def set_article
        @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    def require_same_user
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can edit or delete only your articles"
            redirect_to root_path
        end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    before_action :set_category, only: [:edit, :show, :update]
    def index
        @categories = Category.paginate(page: params[:page], per_page: params[:limit])
    end
    def new
        @category = Category.new
    end
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:success] = "New category have been created"
            redirect_to categories_path
        else
            render 'new'
        end
    end

    def edit 
    end
    
    def update
        if @category.update(category_params)
            flash[:success] = "Category was succesfully updated"    
            redirect_to category_path(@category.id)
        else
            render 'edit'
        end
    end

    def show
        @category_articles = @category.articles.paginate(page: params[:page], per_page: params[:limit])
    end 
    private
    def set_category
        @category = Category.find(params[:id])
    end
    def category_params
        params.require(:category).permit(:name)
    end  
    def require_admin
        if !logged_in? || (logged_in? && !current_user.admin?)
            flash[:danger] = "Admin only action"
            redirect_to categories_path
        end
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:session][:email].downcase)
        if @user && @user.authenticate(params[:session][:password])
            flash[:success] = "You are loged in succesfully"
            session[:user_id] = @user.id    
            redirect_to user_path(@user)
        else
            flash[:danger] = "Invalid email or password"    
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You are loged out succesfully"
        redirect_to root_path
    end    
    private 
        def session_params
            params.require(:session).permit(:email, :password)
        end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :update, :show]
    before_action :require_same_user, only: [:edit, :update]
    before_action :require_admin, only: [:destroy]
    def new        
        @user = User.new
    end
    def create        
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to my Blog app #{@user.username}"   
            session[:user_id] = @user.id  
            redirect_to user_path(@user)
        else
            render 'new'
        end 
    end
    def edit 
    end
    def show 
        @user_articles = @user.articles.paginate(page: params[:page], per_page: params[:limit])
    end
    def index 
        @users = User.paginate(page: params[:page], per_page: params[:limit])
    end
    def update
        if @user.update(user_params)
            flash[:success] = "Your info was succesfully updated"    
            redirect_to root_path
        else
            render 'edit'
        end
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        flash[:danger] = "#{@user.username} is succesfully deleted"
        if current_user == @user
            session[:user_id] = nil
        end
        redirect_to users_path
    end
    
    private 
        def user_params
            params.require(:user).permit(:email, :username, :password)
        end
        def set_user
            @user = User.find(params[:id])
        end
        def require_same_user
            if current_user != @user
                flash[:danger] = "You can edit your account only"
                redirect_to root_path
            end
        end
        def require_admin
            if logged_in?  && !current_user.admin?
                flash[:danger] = "Admin only action"
                redirect_to root_path
            end
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home
        redirect_to articles_path if logged_in?
        
    end
    
    def about
    
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for user, options = {size: 80}

        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "img-circle")
    end
    
end

app/views/articles/_article.html.erb
<% object.each do |article|%>
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to article.title, article_path(article.id) %>
            </div>
            <div class="article-body">
                <%= truncate(article.description, length: 100) %>
                <div class="meta-cearte">
                    <small>
                        Created by : <%= article.user.username%>, 
                        <%= time_ago_in_words(article.created_at)%> ago, 
                        last update <%= time_ago_in_words(article.updated_at) %> ago
                    </small>
                </div>
            </div>
              <% if article.categories.any? %>
                <p>Categories: <%= render article.categories %></p>
            <% end %>
            <% if logged_in? && (current_user == article.user || current_user.admin?) %>
               <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
               <%= link_to "Delete this article", article_path(article), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete this article?" }, 
                                          class: "btn btn-xs btn-danger" %>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', object: @article %>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>  
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
        </div>
      </div>   
      <div class="form-group">
        <div class="row">
          <div class="col-sm-8 col-sm-offset-2">
            <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text } %>
            <% end %>
          </div>
        </div>
      </div>
        <div class="form-group">
                <div class="col-sm-8 col-sm-offset-2">
                    <%= f.submit class: "btn btn-danger btn-lg btn-xlarg-2" %>
                </div>
        </div>      
          <div class="col-sm-8 col-sm-offset-2">
            <%= link_to "Back to articles listing",   articles_path, class: "link" %>    
        </div>
        <% end %>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit an article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Articles</h1>
<%= render 'article', object: @articles %>
<div class="center">
    <%= will_paginate @articles%>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"> Title : <%= @article.title%> </h2>
<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong>Description:</strong></h4>
    <hr>
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
    <% end %>
    <div class="article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
            <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
            <%= link_to "Delete this article", article_path(@article), method: :delete, 
                                            data: { confirm: "Are you sure you want to delete this article?" }, 
                                            class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
    </div>
</div>

app/views/categories/_category.html.erb
<span class="badge">
 <%= link_to category.name, category_path(category.id)%> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', object: @category %>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                <%= f.label :name %>  
                </div>
                <div class="col-sm-8">
                <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
                </div>
            </div>
            </div>   
            <div class="form-group">
                <div class="col-sm-8 col-sm-offset-2">
                    <%= f.submit class: "btn btn-danger btn-lg btn-xlarg-2" %>
                </div>
            </div>      
             <div class="col-sm-8 col-sm-offset-2">
                <%= link_to "Back to articles listing",   articles_path, class: "link" %>    
            </div>
        <% end %>
    </div>
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit a Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">listing All Categories</h1>
<div class="center">
    <% @categories.each do |category|%>
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
            <div class="well well-lg">
                <div class="article-title">
                    <%= link_to category.name, category_path(category.id) %>
                </div>
                <small><%= pluralize(category.articles.count, "article") %></small>
            </div>
        </div>
    </div>
    <% end %>
</div>
<div class="center">
    <%= will_paginate @categories%>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create a Category</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h2 align="center"> Category: <%= @category.name%> </h2>
<% if logged_in? && current_user.admin?%>
    <div class="center">
        <div class="row">
            <span class="badge"><%= link_to "Update category name", edit_category_path(@category.id) %></span>
        </div>  
    </div>
<% end %>
<%= render 'articles/article', object: @category_articles %>
<div class="center">
    <%= will_paginate @category_articles%>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
            Copyrights &copy; <a href="https://alaa-blog-2021.herokuapp.com">My Blog App</a>
            by <a href="https://github.com/MuhammeedAlaa">Muhammeed Alaa</a>
        </small>
        <nav>
            <ul>
                <li>
                    <%= link_to 'About' , about_path %> 
                </li>        
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
  
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>  
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "My Blog", root_path, class: "navbar-brand", id: "name" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %> </li>
        <li><%= link_to "users", users_path %> </li>
        <li><%= link_to "All Categories", categories_path %></li>
        <% if logged_in?%>
          <li><%= link_to "New article", new_article_path %> </li>
        <% end %>
         <% if logged_in? && current_user.admin? %>
              <li><%= link_to "Create New Category", new_category_path %></li>
          <% end %>

      </ul>

      
      <% if logged_in?%>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Edit Profile", edit_user_path(current_user)%></li>
        <li><%= link_to  current_user.admin? ? "Admin Profile" : "Profile", user_path(current_user) %></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
      </ul>
      <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Log In", login_path%></li>
        <li><%= link_to "Sign up", signup_path%></li>
      </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <div class="container">
     <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(object.errors.count, "Error") %>
            The following error prevent the article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>
<div class="row">
    <div class="col-xs-12">
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                <%= f.label :email %>  
                </div>
                <div class="col-sm-8">
                <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                <%= f.label :username %>  
                </div>
                <div class="col-sm-8">
                <%= f.text_field :username, class: "form-control", placeholder: "User Name", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                <%= f.label :password %>
                </div>
                <div class="col-sm-8">
                <%= f.password_field :password, rows: 10, class: "form-control", placeholder: "Password" %>
                </div>
            </div>   
            <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-2">
                        <%= f.submit(@user.new_record?  ? "Sign up" : "Update Account", class: "btn btn-danger btn-lg btn-xlarg-2") %>
                    </div>
            </div>      
            <div class="col-sm-8 col-sm-offset-2 mrg-bt">
                <%= link_to "Back to Home",   root_path, class: "link" %>    
            </div>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<div class="panel panel-default center bg-clr">
    <div class="mrg-tp">
        <h1 align="center">Edit your info</h1>
        <%= render 'form' %>
    </div>
</div>

app/views/users/index.html.erb
<div class="center">  
  <h1 align="center">All Users</h1>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(user), user_path(user) %></li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
             <% if logged_in? && current_user.admin?  %>
               <%= link_to "Delete this user", user_path(user), method: :delete, 
                                          data: { confirm: "Are you sure you want to delete this user ?" }, 
                                          class: "btn btn-xs btn-danger" %>
            <% end %>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate @users %>
</div>

app/views/users/new.html.erb
<div class="panel panel-default center bg-clr">
    <div class="mrg-tp">
        <h1 align="center">Sign Up</h1>
        <%= render 'shared/errors', object: @user %>
        <div class="row">
            <div class="col-xs-12">
                <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-sm-2">
                <%= f.label :email %>  
                </div>
                <div class="col-sm-8">
                <%= f.email_field :email, class: "form-control", placeholder: "Email", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                <%= f.label :username %>  
                </div>
                <div class="col-sm-8">
                <%= f.text_field :username, class: "form-control", placeholder: "User Name", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-sm-2">
                <%= f.label :password %>
                </div>
                <div class="col-sm-8">
                <%= f.password_field :password, rows: 10, class: "form-control", placeholder: "Password" %>
                </div>
            </div>   
                    <div class="form-group">
                            <div class="col-sm-8 col-sm-offset-2">
                                <%= f.submit "Sign up", class: "btn btn-danger btn-lg btn-xlarg-2" %>
                            </div>
                    </div>      
                    <div class="col-sm-8 col-sm-offset-2 mrg-bt">
                        <%= link_to "Back to Home",   root_path, class: "link" %>    
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<h1 align="center">Welecome to <%=@user.username%>'s page</h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for(@user, size: 200)%>
    </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<%= render '/articles/article', object: @user_articles %>
<div class="center">
    <%= will_paginate @user_articles%>
</div>

app/views/welcome/about.html.erb
<h1>This is the about page of My Blog App</h1>
<ul class="listing">
    <li>
        <h3>
            This is an app that has users that can sign in and sign up and create thier aricles in different categories
        </h3>
    </li>
    <li>
        <h3>
            This app has an admin who can edit or delete articles as well as the user who created it if he sees that they violate any rule
        </h3>
    </li>
</ul>
<%= link_to 'Home' , root_path %>

app/views/welcome/home.html.erb
<div class="jumbotron center">
    <h1>My Blog App</h1>
    <%= link_to 'Sign Up' , signup_path , class: 'btn btn-danger btn-lg btn-xlarg'%>
</div>